# Generated by Django 6.1.1 on 2026-10-05 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveSmallIntegerField(default=1)),
                ('day_name', models.CharField(blank=True, max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('sets', models.PositiveSmallIntegerField(default=3)),
                ('reps', models.CharField(default='8-12', max_length=20)),
            ],
            options={
                'ordering': ['day_number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('days_per_week', models.PositiveSmallIntegerField(choices=[(2, '2 days'), (3, '3 days'), (4, '4 days'), (5, '5 days'), (6, '6 days')])),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Workout',
        ),
        migrations.AddField(
            model_name='templateexercise',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='tracker.workouttemplate'),
        ),
    ]
